# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_rcss')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_rcss')
    _rcss = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rcss', [dirname(__file__)])
        except ImportError:
            import _rcss
            return _rcss
        try:
            _mod = imp.load_module('_rcss', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _rcss = swig_import_helper()
    del swig_import_helper
else:
    import _rcss
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class ServerParam(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ServerParam, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ServerParam, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        instance = staticmethod(_rcss.ServerParam_instance)
    else:
        instance = _rcss.ServerParam_instance
    if _newclass:
        init = staticmethod(_rcss.ServerParam_init)
    else:
        init = _rcss.ServerParam_init
    __swig_destroy__ = _rcss.delete_ServerParam
    __del__ = lambda self: None

    def clear(self):
        return _rcss.ServerParam_clear(self)

    def verMap(self):
        return _rcss.ServerParam_verMap(self)

    def setRandomSeed(self, seed):
        return _rcss.ServerParam_setRandomSeed(self, seed)

    def convertToStruct(self):
        return _rcss.ServerParam_convertToStruct(self)

    def getInt(self, param, value):
        return _rcss.ServerParam_getInt(self, param, value)

    def getBool(self, param, value):
        return _rcss.ServerParam_getBool(self, param, value)

    def getDouble(self, param, value):
        return _rcss.ServerParam_getDouble(self, param, value)

    def getStr(self, param, value):
        return _rcss.ServerParam_getStr(self, param, value)

    def goalWidth(self):
        return _rcss.ServerParam_goalWidth(self)

    def inertiaMoment(self):
        return _rcss.ServerParam_inertiaMoment(self)

    def playerSize(self):
        return _rcss.ServerParam_playerSize(self)

    def playerDecay(self):
        return _rcss.ServerParam_playerDecay(self)

    def playerRand(self):
        return _rcss.ServerParam_playerRand(self)

    def playerWeight(self):
        return _rcss.ServerParam_playerWeight(self)

    def playerSpeedMax(self):
        return _rcss.ServerParam_playerSpeedMax(self)

    def playerAccelMax(self):
        return _rcss.ServerParam_playerAccelMax(self)

    def staminaMax(self):
        return _rcss.ServerParam_staminaMax(self)

    def staminaInc(self):
        return _rcss.ServerParam_staminaInc(self)

    def recoverInit(self):
        return _rcss.ServerParam_recoverInit(self)

    def recoverDecThr(self):
        return _rcss.ServerParam_recoverDecThr(self)

    def recoverMin(self):
        return _rcss.ServerParam_recoverMin(self)

    def recoverDec(self):
        return _rcss.ServerParam_recoverDec(self)

    def effortInit(self):
        return _rcss.ServerParam_effortInit(self)

    def effortDecThr(self):
        return _rcss.ServerParam_effortDecThr(self)

    def effortMin(self):
        return _rcss.ServerParam_effortMin(self)

    def effortDec(self):
        return _rcss.ServerParam_effortDec(self)

    def effortIncThr(self):
        return _rcss.ServerParam_effortIncThr(self)

    def effortInc(self):
        return _rcss.ServerParam_effortInc(self)

    def kickRand(self):
        return _rcss.ServerParam_kickRand(self)

    def teamActuatorNoise(self):
        return _rcss.ServerParam_teamActuatorNoise(self)

    def playerRandFactorLeft(self):
        return _rcss.ServerParam_playerRandFactorLeft(self)

    def playerRandFactorRight(self):
        return _rcss.ServerParam_playerRandFactorRight(self)

    def kickRandFactorLeft(self):
        return _rcss.ServerParam_kickRandFactorLeft(self)

    def kickRandFactorRight(self):
        return _rcss.ServerParam_kickRandFactorRight(self)

    def ballSize(self):
        return _rcss.ServerParam_ballSize(self)

    def ballDecay(self):
        return _rcss.ServerParam_ballDecay(self)

    def ballRand(self):
        return _rcss.ServerParam_ballRand(self)

    def ballWeight(self):
        return _rcss.ServerParam_ballWeight(self)

    def ballSpeedMax(self):
        return _rcss.ServerParam_ballSpeedMax(self)

    def ballAccelMax(self):
        return _rcss.ServerParam_ballAccelMax(self)

    def dashPowerRate(self):
        return _rcss.ServerParam_dashPowerRate(self)

    def kickPowerRate(self):
        return _rcss.ServerParam_kickPowerRate(self)

    def kickableMargin(self):
        return _rcss.ServerParam_kickableMargin(self)

    def controlRadius(self):
        return _rcss.ServerParam_controlRadius(self)

    def controlRadiusWidth(self):
        return _rcss.ServerParam_controlRadiusWidth(self)

    def maxPower(self):
        return _rcss.ServerParam_maxPower(self)

    def minPower(self):
        return _rcss.ServerParam_minPower(self)

    def maxMoment(self):
        return _rcss.ServerParam_maxMoment(self)

    def minMoment(self):
        return _rcss.ServerParam_minMoment(self)

    def maxNeckMoment(self):
        return _rcss.ServerParam_maxNeckMoment(self)

    def minNeckMoment(self):
        return _rcss.ServerParam_minNeckMoment(self)

    def maxNeckAngle(self):
        return _rcss.ServerParam_maxNeckAngle(self)

    def minNeckAngle(self):
        return _rcss.ServerParam_minNeckAngle(self)

    def visibleAngleDegree(self):
        return _rcss.ServerParam_visibleAngleDegree(self)

    def visibleDistance(self):
        return _rcss.ServerParam_visibleDistance(self)

    def windDir(self):
        return _rcss.ServerParam_windDir(self)

    def windForce(self):
        return _rcss.ServerParam_windForce(self)

    def windAngle(self):
        return _rcss.ServerParam_windAngle(self)

    def windRand(self):
        return _rcss.ServerParam_windRand(self)

    def windWeight(self):
        return _rcss.ServerParam_windWeight(self)

    def windNone(self):
        return _rcss.ServerParam_windNone(self)

    def windRandom(self):
        return _rcss.ServerParam_windRandom(self)

    def kickableArea(self):
        return _rcss.ServerParam_kickableArea(self)

    def catchAreaLength(self):
        return _rcss.ServerParam_catchAreaLength(self)

    def catchAreaWidth(self):
        return _rcss.ServerParam_catchAreaWidth(self)

    def catchProbability(self):
        return _rcss.ServerParam_catchProbability(self)

    def goalieMaxMoves(self):
        return _rcss.ServerParam_goalieMaxMoves(self)

    def keepAwayMode(self):
        return _rcss.ServerParam_keepAwayMode(self)

    def keepAwayLength(self):
        return _rcss.ServerParam_keepAwayLength(self)

    def keepAwayWidth(self):
        return _rcss.ServerParam_keepAwayWidth(self)

    def cornerKickMargin(self):
        return _rcss.ServerParam_cornerKickMargin(self)

    def offsideActiveArea(self):
        return _rcss.ServerParam_offsideActiveArea(self)

    def playerPort(self):
        return _rcss.ServerParam_playerPort(self)

    def offlineCoachPort(self):
        return _rcss.ServerParam_offlineCoachPort(self)

    def onlineCoachPort(self):
        return _rcss.ServerParam_onlineCoachPort(self)

    def freeformCountMax(self):
        return _rcss.ServerParam_freeformCountMax(self)

    def freeformMsgSize(self):
        return _rcss.ServerParam_freeformMsgSize(self)

    def clangWinSize(self):
        return _rcss.ServerParam_clangWinSize(self)

    def clangDefineWin(self):
        return _rcss.ServerParam_clangDefineWin(self)

    def clangMetaWin(self):
        return _rcss.ServerParam_clangMetaWin(self)

    def clangAdviceWin(self):
        return _rcss.ServerParam_clangAdviceWin(self)

    def clangInfoWin(self):
        return _rcss.ServerParam_clangInfoWin(self)

    def clangMessDelay(self):
        return _rcss.ServerParam_clangMessDelay(self)

    def clangMessPerCycle(self):
        return _rcss.ServerParam_clangMessPerCycle(self)

    def halfTime(self):
        return _rcss.ServerParam_halfTime(self)

    def dropTime(self):
        return _rcss.ServerParam_dropTime(self)

    def nrNormalHalfs(self):
        return _rcss.ServerParam_nrNormalHalfs(self)

    def nrExtraHalfs(self):
        return _rcss.ServerParam_nrExtraHalfs(self)

    def penaltyShootOuts(self):
        return _rcss.ServerParam_penaltyShootOuts(self)

    def penBeforeSetupWait(self):
        return _rcss.ServerParam_penBeforeSetupWait(self)

    def penSetupWait(self):
        return _rcss.ServerParam_penSetupWait(self)

    def penReadyWait(self):
        return _rcss.ServerParam_penReadyWait(self)

    def penTakenWait(self):
        return _rcss.ServerParam_penTakenWait(self)

    def penNrKicks(self):
        return _rcss.ServerParam_penNrKicks(self)

    def penMaxExtraKicks(self):
        return _rcss.ServerParam_penMaxExtraKicks(self)

    def penDistX(self):
        return _rcss.ServerParam_penDistX(self)

    def penRandomWinner(self):
        return _rcss.ServerParam_penRandomWinner(self)

    def penAllowMultiKicks(self):
        return _rcss.ServerParam_penAllowMultiKicks(self)

    def penMaxGoalieDistX(self):
        return _rcss.ServerParam_penMaxGoalieDistX(self)

    def penCoachMovesPlayers(self):
        return _rcss.ServerParam_penCoachMovesPlayers(self)

    def simStep(self):
        return _rcss.ServerParam_simStep(self)

    def senseBodyStep(self):
        return _rcss.ServerParam_senseBodyStep(self)

    def coachVisualStep(self):
        return _rcss.ServerParam_coachVisualStep(self)

    def sendStep(self):
        return _rcss.ServerParam_sendStep(self)

    def lcmStep(self):
        return _rcss.ServerParam_lcmStep(self)

    def recvStep(self):
        return _rcss.ServerParam_recvStep(self)

    def catchBanCycle(self):
        return _rcss.ServerParam_catchBanCycle(self)

    def slowDownFactor(self):
        return _rcss.ServerParam_slowDownFactor(self)

    def useOffside(self):
        return _rcss.ServerParam_useOffside(self)

    def kickOffOffside(self):
        return _rcss.ServerParam_kickOffOffside(self)

    def offsideKickMargin(self):
        return _rcss.ServerParam_offsideKickMargin(self)

    def audioCutDist(self):
        return _rcss.ServerParam_audioCutDist(self)

    def quantizeStep(self):
        return _rcss.ServerParam_quantizeStep(self)

    def landmarkQuantizeStep(self):
        return _rcss.ServerParam_landmarkQuantizeStep(self)

    def verboseMode(self):
        return _rcss.ServerParam_verboseMode(self)

    def coachMode(self):
        return _rcss.ServerParam_coachMode(self)

    def coachWithRefereeMode(self):
        return _rcss.ServerParam_coachWithRefereeMode(self)

    def coachOldHear(self):
        return _rcss.ServerParam_coachOldHear(self)

    def synchMode(self):
        return _rcss.ServerParam_synchMode(self)

    def synchOffset(self):
        return _rcss.ServerParam_synchOffset(self)

    def synchMicroSleep(self):
        return _rcss.ServerParam_synchMicroSleep(self)

    def startGoalLeft(self):
        return _rcss.ServerParam_startGoalLeft(self)

    def startGoalRight(self):
        return _rcss.ServerParam_startGoalRight(self)

    def fullstateLeft(self):
        return _rcss.ServerParam_fullstateLeft(self)

    def fullstateRight(self):
        return _rcss.ServerParam_fullstateRight(self)

    def slownessOnTopForLeft(self):
        return _rcss.ServerParam_slownessOnTopForLeft(self)

    def slownessOnTopForRight(self):
        return _rcss.ServerParam_slownessOnTopForRight(self)

    def landmarkFile(self):
        return _rcss.ServerParam_landmarkFile(self)

    def sendComms(self):
        return _rcss.ServerParam_sendComms(self)

    def textLogging(self):
        return _rcss.ServerParam_textLogging(self)

    def gameLogging(self):
        return _rcss.ServerParam_gameLogging(self)

    def gameLogVersion(self):
        return _rcss.ServerParam_gameLogVersion(self)

    def textLogDir(self):
        return _rcss.ServerParam_textLogDir(self)

    def gameLogDir(self):
        return _rcss.ServerParam_gameLogDir(self)

    def textLogFixedName(self):
        return _rcss.ServerParam_textLogFixedName(self)

    def gameLogFixedName(self):
        return _rcss.ServerParam_gameLogFixedName(self)

    def textLogFixed(self):
        return _rcss.ServerParam_textLogFixed(self)

    def gameLogFixed(self):
        return _rcss.ServerParam_gameLogFixed(self)

    def textLogDated(self):
        return _rcss.ServerParam_textLogDated(self)

    def gameLogDated(self):
        return _rcss.ServerParam_gameLogDated(self)

    def logDateFormat(self):
        return _rcss.ServerParam_logDateFormat(self)

    def logTimes(self):
        return _rcss.ServerParam_logTimes(self)

    def recordMessages(self):
        return _rcss.ServerParam_recordMessages(self)

    def textLogCompression(self):
        return _rcss.ServerParam_textLogCompression(self)

    def gameLogCompression(self):
        return _rcss.ServerParam_gameLogCompression(self)

    def profile(self):
        return _rcss.ServerParam_profile(self)

    def kawayLogging(self):
        return _rcss.ServerParam_kawayLogging(self)

    def kawayLogDir(self):
        return _rcss.ServerParam_kawayLogDir(self)

    def kawayLogFixedName(self):
        return _rcss.ServerParam_kawayLogFixedName(self)

    def kawayLogFixed(self):
        return _rcss.ServerParam_kawayLogFixed(self)

    def kawayLogDated(self):
        return _rcss.ServerParam_kawayLogDated(self)

    def kawayStart(self):
        return _rcss.ServerParam_kawayStart(self)

    def pointToBan(self):
        return _rcss.ServerParam_pointToBan(self)

    def pointToDuration(self):
        return _rcss.ServerParam_pointToDuration(self)

    def sayMsgSize(self):
        return _rcss.ServerParam_sayMsgSize(self)

    def hearMax(self):
        return _rcss.ServerParam_hearMax(self)

    def hearInc(self):
        return _rcss.ServerParam_hearInc(self)

    def hearDecay(self):
        return _rcss.ServerParam_hearDecay(self)

    def tackleDist(self):
        return _rcss.ServerParam_tackleDist(self)

    def tackleBackDist(self):
        return _rcss.ServerParam_tackleBackDist(self)

    def tackleWidth(self):
        return _rcss.ServerParam_tackleWidth(self)

    def tackleExponent(self):
        return _rcss.ServerParam_tackleExponent(self)

    def tackleCycles(self):
        return _rcss.ServerParam_tackleCycles(self)

    def tacklePowerRate(self):
        return _rcss.ServerParam_tacklePowerRate(self)

    def freeformWaitPeriod(self):
        return _rcss.ServerParam_freeformWaitPeriod(self)

    def freeformSendPeriod(self):
        return _rcss.ServerParam_freeformSendPeriod(self)

    def freeKickFaults(self):
        return _rcss.ServerParam_freeKickFaults(self)

    def backPasses(self):
        return _rcss.ServerParam_backPasses(self)

    def properGoalKicks(self):
        return _rcss.ServerParam_properGoalKicks(self)

    def stoppedBallVel(self):
        return _rcss.ServerParam_stoppedBallVel(self)

    def maxGoalKicks(self):
        return _rcss.ServerParam_maxGoalKicks(self)

    def clangDelWin(self):
        return _rcss.ServerParam_clangDelWin(self)

    def clangRuleWin(self):
        return _rcss.ServerParam_clangRuleWin(self)

    def autoMode(self):
        return _rcss.ServerParam_autoMode(self)

    def kickOffWait(self):
        return _rcss.ServerParam_kickOffWait(self)

    def connectWait(self):
        return _rcss.ServerParam_connectWait(self)

    def gameOverWait(self):
        return _rcss.ServerParam_gameOverWait(self)

    def teamLeftStart(self):
        return _rcss.ServerParam_teamLeftStart(self)

    def teamRightStart(self):
        return _rcss.ServerParam_teamRightStart(self)

    def goalPostRadius(self):
        return _rcss.ServerParam_goalPostRadius(self)

    def ballStuckArea(self):
        return _rcss.ServerParam_ballStuckArea(self)

    def coachMsgFile(self):
        return _rcss.ServerParam_coachMsgFile(self)

    def maxTacklePower(self):
        return _rcss.ServerParam_maxTacklePower(self)

    def maxBackTacklePower(self):
        return _rcss.ServerParam_maxBackTacklePower(self)

    def playerSpeedMaxMin(self):
        return _rcss.ServerParam_playerSpeedMaxMin(self)

    def extraStamina(self):
        return _rcss.ServerParam_extraStamina(self)

    def maxMonitors(self):
        return _rcss.ServerParam_maxMonitors(self)

    def synchSeeOffset(self):
        return _rcss.ServerParam_synchSeeOffset(self)

    def extraHalfTime(self):
        return _rcss.ServerParam_extraHalfTime(self)

    def staminaCapacity(self):
        return _rcss.ServerParam_staminaCapacity(self)

    def maxDashAngle(self):
        return _rcss.ServerParam_maxDashAngle(self)

    def minDashAngle(self):
        return _rcss.ServerParam_minDashAngle(self)

    def dashAngleStep(self):
        return _rcss.ServerParam_dashAngleStep(self)

    def sideDashRate(self):
        return _rcss.ServerParam_sideDashRate(self)

    def backDashRate(self):
        return _rcss.ServerParam_backDashRate(self)

    def maxDashPower(self):
        return _rcss.ServerParam_maxDashPower(self)

    def minDashPower(self):
        return _rcss.ServerParam_minDashPower(self)

    def tackleRandFactor(self):
        return _rcss.ServerParam_tackleRandFactor(self)

    def foulDetectProbability(self):
        return _rcss.ServerParam_foulDetectProbability(self)

    def foulExponent(self):
        return _rcss.ServerParam_foulExponent(self)

    def foulCycles(self):
        return _rcss.ServerParam_foulCycles(self)

    def randomSeed(self):
        return _rcss.ServerParam_randomSeed(self)

    def goldenGoal(self):
        return _rcss.ServerParam_goldenGoal(self)

    def redCardProbability(self):
        return _rcss.ServerParam_redCardProbability(self)

    def longKickPowerFactor(self):
        return _rcss.ServerParam_longKickPowerFactor(self)

    def longKickDelay(self):
        return _rcss.ServerParam_longKickDelay(self)
ServerParam_swigregister = _rcss.ServerParam_swigregister
ServerParam_swigregister(ServerParam)

def ServerParam_instance():
    return _rcss.ServerParam_instance()
ServerParam_instance = _rcss.ServerParam_instance

def ServerParam_init(argc, argv):
    return _rcss.ServerParam_init(argc, argv)
ServerParam_init = _rcss.ServerParam_init
cvar = _rcss.cvar
ServerParam.PITCH_LENGTH = _rcss.cvar.ServerParam_PITCH_LENGTH
ServerParam.PITCH_WIDTH = _rcss.cvar.ServerParam_PITCH_WIDTH
ServerParam.PITCH_MARGIN = _rcss.cvar.ServerParam_PITCH_MARGIN
ServerParam.CENTER_CIRCLE_R = _rcss.cvar.ServerParam_CENTER_CIRCLE_R
ServerParam.PENALTY_AREA_LENGTH = _rcss.cvar.ServerParam_PENALTY_AREA_LENGTH
ServerParam.PENALTY_AREA_WIDTH = _rcss.cvar.ServerParam_PENALTY_AREA_WIDTH
ServerParam.GOAL_AREA_LENGTH = _rcss.cvar.ServerParam_GOAL_AREA_LENGTH
ServerParam.GOAL_AREA_WIDTH = _rcss.cvar.ServerParam_GOAL_AREA_WIDTH
ServerParam.GOAL_WIDTH = _rcss.cvar.ServerParam_GOAL_WIDTH
ServerParam.GOAL_DEPTH = _rcss.cvar.ServerParam_GOAL_DEPTH
ServerParam.PENALTY_SPOT_DIST = _rcss.cvar.ServerParam_PENALTY_SPOT_DIST
ServerParam.CORNER_ARC_R = _rcss.cvar.ServerParam_CORNER_ARC_R
ServerParam.KICK_OFF_CLEAR_DISTANCE = _rcss.cvar.ServerParam_KICK_OFF_CLEAR_DISTANCE
ServerParam.CORNER_KICK_MARGIN = _rcss.cvar.ServerParam_CORNER_KICK_MARGIN

# This file is compatible with both classic and new-style classes.


